{% set name = "mrcfile" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 689bb3a094500d0025abb0bcb24b75558dde3f68fe659c8d610b15aa6180dbc9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - numpy >=1.11.0
    - pip
    - python
  run:
    - numpy >=1.11.0
    - python

test:
  imports:
    - mrcfile

about:
  home: https://github.com/ccpem/mrcfile
  license: BSD
  license_family: BSD
  license_file:
  summary: MRC file I/O library
  description: A Python implementation of the MRC2014 file format
  doc_url: https://github.com/ccpem/mrcfile
  dev_url: https://github.com/ccpem/mrcfile

extra:
  recipe-maintainers:
    - bkpoon
